portfolio_lab/portfolio_lab/urls.py
from os import name
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as django_auth_views

from app_portfolio.views import (
    LandingPageView,
    DonationFormView,
    LoginView,
    RegisterView,
    dontaion_form_confirmation_view,
    user_detail_view,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", LandingPageView.as_view(), name="index"),
    path("add_donation/<user_id>", DonationFormView.as_view(), name="add-donation"),
    path("donation_confirmed/", dontaion_form_confirmation_view, name="from-confirm"),
    path("login/", LoginView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("logout/", django_auth_views.LogoutView.as_view(next_page="/"), name="logout"),
    path("user/<int:user_id>", user_detail_view, name="user-detail"),
]

portfolio_lab/app_portfolio/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

import datetime

INSTITUTION_TYPES = (
    (1, "Fundation"),
    (2, "Non-goverment organization"),
    (3, "Local collection"),
)


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Institution(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    type = models.IntegerField(choices=INSTITUTION_TYPES, default=1)
    categories = models.ManyToManyField(Category, related_name="institutions")

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.IntegerField()
    categories = models.ManyToManyField(Category, related_name="donations")
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    phone_number = models.IntegerField()
    city = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=6)
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField()
    pick_up_comment = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=None)

    def save(self, *args, **kwargs):
        if self.pick_up_date < datetime.date.today():
            raise ValidationError("Data nie może być z przeszłości!")
        super(Donation, self).save(*args, **kwargs)

portfolio_lab/app_portfolio/forms.py
from django import forms
from django.core.validators import EmailValidator
from django.forms import widgets
from app_portfolio.models import Category, Institution


class RegistrationForm(forms.Form):
    name = forms.CharField(
        max_length=150, widget=forms.TextInput(attrs={"placeholder": "Imię"})
    )
    surname = forms.CharField(
        max_length=150, widget=forms.TextInput(attrs={"placeholder": "Nazwisko"})
    )
    email = forms.EmailField(
        max_length=150,
        widget=forms.TextInput(attrs={"placeholder": "Email"}),
        validators=[EmailValidator],
    )
    password = forms.CharField(
        max_length=150, widget=forms.PasswordInput(attrs={"placeholder": "Hasło"})
    )
    password2 = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput(attrs={"placeholder": "Powtórz hasło"}),
    )


class LoginForm(forms.Form):
    email = forms.EmailField(
        max_length=150,
        widget=forms.TextInput(attrs={"placeholder": "Email"}),
        validators=[EmailValidator],
    )
    password = forms.CharField(
        max_length=150, widget=forms.PasswordInput(attrs={"placeholder": "Hasło"})
    )


class DonationForm(forms.Form):
    amount_of_bags = forms.IntegerField(min_value=1, required=True)
    street = forms.CharField(max_length=150, required=True)
    city = forms.CharField(max_length=100, required=True)
    postal_code = forms.RegexField(regex="[0-9]{2}-[0-9]{3}", required=True)
    phone_number = forms.RegexField(regex="[0-9]{9}", required=True)
    pickup_date = forms.DateField(
        required=True, widget=forms.DateInput(attrs={"type": "date"})
    )
    pickup_time = forms.TimeField(
        required=True, widget=forms.TimeInput(attrs={"type": "time"})
    )
    additional_pickup_information = forms.CharField(
        widget=forms.Textarea(attrs={"rows": "5"}), required=False
    )

portfolio_lab/app_portfolio/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.db.models.lookups import In
from django.shortcuts import redirect, render
from django.views import View
from django.contrib.auth import login, authenticate
from django.contrib import messages


from app_portfolio.forms import LoginForm, RegistrationForm, DonationForm
from app_portfolio.models import Category, Donation, Institution


def dontaion_form_confirmation_view(request):
    return render(request, "form-confirmation.html")


@login_required
def user_detail_view(request, user_id):
    user = User.objects.get(pk=user_id)
    return render(request, "user-details.html", {"user": user})


class LandingPageView(View):
    def get(self, request):
        donated_bags = Donation.objects.count()
        ctx = {"donated_bags": donated_bags}
        return render(request, "index.html", ctx)


class DonationFormView(LoginRequiredMixin, View):
    """Class for handling donation form and creation of donation objects,
    if form was validated successfully
    """

    def get(self, request, user_id):
        form = DonationForm()
        ctx = {"form": form}
        return render(request, "form.html", ctx)

    def post(self, request, user_id):
        """Method handling POST request

        Args:
            user_id (Int): id of logged user

        Returns:
            If donation form is valid, returns user to confirmation site,
            else return empty form and information about an error via
            messeges framework
        """
        form = DonationForm(request.POST)
        user = User.objects.get(pk=user_id)
        if (
            form.is_valid()
            and request.POST.get("categories")
            and request.POST.get("organization")
        ):
            try:
                DonationFormView.get_form_data_and_create_donation(request, form, user)
            except ValidationError:
                messages.add_message(
                    request, messages.WARNING, "Data nie może być z przeszłości!"
                )
                return render(request, "form.html", {"form": DonationForm()})
            return redirect("/donation_confirmed/")
        messages.add_message(
            request, messages.WARNING, "Wystąpił błąd, wypełnij formularz ponownie"
        )
        return render(request, "form.html", {"form": DonationForm()})

    @staticmethod
    def get_form_data_and_create_donation(request, form, user):
        """
        Class method for checking if date field is valid,
        and if yes, creates new donation object.

        Args:
            form (Form): DonationForm with request.POST data
            user (User): Logged user object

        Raises:
            ValidationError: if date field is from the past, save() raises
            ValidationError.
        """
        chosen_categories = request.POST.getlist("categories")
        amount_of_bags = int(form.cleaned_data["amount_of_bags"])
        chosen_organization = request.POST.get("organization")
        street = form.cleaned_data["street"]
        city = form.cleaned_data["city"]
        postal_code = form.cleaned_data["postal_code"]
        phone_number = int(form.cleaned_data["phone_number"])
        pickup_date = form.cleaned_data["pickup_date"]
        pickup_time = form.cleaned_data["pickup_time"]
        additional_pickup_information = form.cleaned_data[
            "additional_pickup_information"
        ]
        # Filing up donation object with data to prepare it for
        # save() validation
        new_donation = Donation()
        new_donation.quantity = amount_of_bags
        new_donation.institution = Institution.objects.get(pk=int(chosen_organization))
        new_donation.address = street
        new_donation.phone_number = phone_number
        new_donation.city = city
        new_donation.zip_code = postal_code
        new_donation.pick_up_date = pickup_date
        new_donation.pick_up_time = pickup_time
        new_donation.pick_up_comment = additional_pickup_information
        new_donation.user = user
        try:
            # first save to check if date is not from the past
            # as save() returns ValidationError if date is from past
            new_donation.save()
            for item in chosen_categories:
                new_donation.categories.add(Category.objects.get(pk=int(item)))
            # second save for updating ManyToMany category field
            new_donation.save()
        except ValidationError as err:
            raise ValidationError("Data nie może być z przeszłości!")


class LoginView(View):
    """View for logging in user."""

    def get(self, request):
        form = LoginForm()
        return render(request, "login.html", {"form": form})

    def post(self, request):
        """Method handling POST request

        Returns:
            If user was logged in, returns to index, if credentials where wrong,
            but login was correct, returns to login. If email is not in db,
            returns to register.
        """
        form = LoginForm(request.POST)
        if form.is_valid():
            login_function = LoginView.login_user(request, form)
            if login_function == 0:
                successfull_login_redirect = request.GET.get("next")
                if successfull_login_redirect:
                    return redirect(successfull_login_redirect)
                return redirect("/")
            elif login_function == 1:
                return redirect("/login/")
            else:
                return redirect("/register/")

        else:
            messages.add_message(
                request, messages.WARNING, "Proszę podać poprawny email"
            )
            return redirect("/login/")

    @staticmethod
    def login_user(request, form):
        """Method for handling logging in

        Args:
            form (Form): Login form with request.POST data

        Returns:
            If logging in was succesfull, returns 0 and logs user,
            if email exists but password was wrong returns 1,
            else returns 2
        """
        email = form.cleaned_data["email"]
        password = form.cleaned_data["password"]
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return 0
        elif user is None and User.objects.filter(email=email).exists():
            messages.add_message(request, messages.WARNING, "Zły email lub hasło")
            return 1
        else:
            messages.add_message(
                request, messages.WARNING, "Nie ma takiego użytkownika"
            )
            return 2


class RegisterView(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, "register.html", {"form": form})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if RegisterView.register_user(request, form):
            # if registering proccess was successfull,
            # returns user to login site
            return redirect("/login/")
        return redirect("/register/")

    @staticmethod
    def register_user(request, form):
        """Method for registering user
        If passwords are not matching, if given email is taken or
        if email is not email format returns error and False,

        Args:
            form (Form): Register form filled with request.POST data

        Returns:
            True, if successfully registered user, else False
        """
        if form.is_valid():
            first_name = form.cleaned_data["name"]
            last_name = form.cleaned_data["surname"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            password2 = form.cleaned_data["password2"]
            if password == password2 and not User.objects.filter(email=email).exists():
                User.objects.create_user(
                    # Username for user is given email address
                    username=email,
                    first_name=first_name,
                    last_name=last_name,
                    email=email,
                    password=password,
                )

                return True
            elif User.objects.filter(email=email).exclude():
                messages.add_message(
                    request, messages.WARNING, "Podany email jest już zajęty!"
                )
                return False
            else:
                messages.add_message(
                    request, messages.WARNING, "Hasła nie są identyczne"
                )
                return False
        else:
            messages.add_message(request, messages.WARNING, "Niepoprawny email")
            return False

portfolio_lab/app_portfolio/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
  {% block account_and_login %}
  {% if user.id %}
      <nav class="container container--70">
        <ul class="nav--actions">
          <li class="logged-user">
            Witaj {{user.first_name}}
            <ul class="dropdown">
              <li><a href="/user/{{user.id}}">Profil</a></li>
              <li><a href="#">Ustawienia</a></li>
              {% if user.is_superuser %}
              <li><a href="/admin/">Panel administracyjny</a></li>
              {% endif %}
              <li><a href="/logout/">Wyloguj</a></li>
              
            </ul>
          </li>
        </ul>
{% else %}
      <nav class="container container--70">
        <ul class="nav--actions">
          <li><a href="/login/" class="btn btn--small btn--without-border">Zaloguj</a></li>
          <li><a href="/register/" class="btn btn--small btn--highlighted">Załóż konto</a></li>
        </ul>
{% endif %}
  {% endblock account_and_login %}
  {% block content %}
  {% endblock content %}
  {% block footer %}
    <footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="{% static 'images/icon-facebook.svg' %}"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="{% static 'images/icon-instagram.svg' %}"
          /></a>
        </div>
      </div>
    </footer>

    <script src="{% static 'js/app.js' %}"></script>
  {% endblock footer %}
  </body>
</html>

portfolio_lab/app_portfolio/templates/form-confirmation.html
{% extends 'base.html' %}
{% load static %}
{% block account_and_login %}
  <header class="header--form-page">
  {{block.super}}
{% endblock account_and_login %}
{% block content %}
        <ul>
          <li><a href="/" class="btn btn--without-border active">Start</a></li>
          <li><a href="/#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="/#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="/#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="/#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>


{% endblock content %}

portfolio_lab/app_portfolio/templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block account_and_login %}
  <header class="header--form-page">
  {{block.super}}
{% endblock account_and_login %}
{% block content %}
        <ul>
          <li><a href="/" class="btn btn--without-border active">Start</a></li>
          <li><a href="/#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="/#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="/#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="/add_donation/" class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="/add_donation/#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>
      {% for message in messages %}
        <h1>{{ message }}</h1>
        {% endfor %}

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>
        
        <form action="/add_donation/{{user.id}}" method="POST">
          {% csrf_token %}
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>
            {% for category in categories %} 
            <div class="form-group form-group--checkbox">
            <label>
                <input
                  type="checkbox"
                  name="categories"
                  value="{{category.id}}"
                  required
                />
                <span class="checkbox"></span>
                 <span class="description"
                  >{{ category.name }}</span
                >  
                </label>
            </div>
             {% endfor %} 
            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                {{ form.amount_of_bags }}
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 3 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>
          {% for institution in institutions %}
            <div class="form-group form-group--checkbox {% for category in institution.categories.all %}{{ category.id }} {% endfor %}">
              <label>
                <input type="radio" name="organization" value="{{ institution.id }}"/>
                <span class="checkbox radio"></span>
                <span class="description">
                  <div class="title">{{ institution.name }}</div>
                  <div class="subtitle">
                    {{ institution.description }}
                  </div>
                </span>
              </label>
            </div>
          {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 4 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica {{ form.street }} </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto {{ form.city }} </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy {{ form.postal_code }}
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu {{ form.phone_number }}
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data {{ form.pickup_date }} </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina {{ form.pickup_time }} </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    {{ form.additional_pickup_information }}
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text"
                      ></span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text"
                      ></span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li></li>
                    <li></li>
                    <li></li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>

{% endblock content %}

portfolio_lab/app_portfolio/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block account_and_login %}
  <header>
  {{block.super}}
{% endblock account_and_login %}
{% block content %}

        <ul>
          <li><a href="/">Start</a></li>
          <li><a href="/#steps">O co chodzi?</a></li>
          <li><a href="/#about-us">O nas</a></li>
          <li><a href="/#help">Fundacje i organizacje</a></li>
          <li><a href="/login/#contact">Kontakt</a></li>
        </ul>
      </nav>
    </header>
 {% if messages %}
    {% for message in messages %}
      <h1>{{message}}</h1>
    {% endfor %}
  {% endif %}
    <section class="login-page">
      <h2>Zaloguj się</h2>
      <form action="" method="POST">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
          {{field}}
        </div>
      {% endfor %}
        <div class="form-group form-group--buttons">
          <a href="/register/" class="btn btn--without-border">Załóż konto</a>
          <button class="btn" type="submit">Zaloguj się</button>
        </div>
        <input type="hidden" name="next" value="{{next}}">
      </form>
    </section>
{% endblock content %}

portfolio_lab/app_portfolio/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block account_and_login %}
  <header>
  {{block.super}}
  </header>
{% endblock account_and_login %}
{% block content %}
    {% if messages %}
    {% for message in messages %}
    <h1>{{message}}</h1>
    {% endfor %}
    {% endif %}
    <section class="login-page">
      <h2>Załóż konto</h2>
      <form action="" method="POST">
        {% csrf_token %}
        {% for filed in form %}
        <div class="form-group">
          {{filed}}
        </div>
        {% endfor %}

        <div class="form-group form-group--buttons">
          <a href="/login/" class="btn btn--without-border">Zaloguj się</a>
          <button class="btn" type="submit">Załóż konto</button>
        </div>
      </form>
    </section>

{% endblock content %}

portfolio_lab/app_portfolio/templates/user-details.html
{% extends 'base.html' %}
{% load static %}
{% block account_and_login %}
<header>
{{ block.super }}
{% endblock account_and_login %}
{% block content %}
    <ul>
          <li><a href="/" class="btn btn--without-border active">Start</a></li>
          <li><a href="/#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="/#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="/#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="/add_donation/" class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="/add_donation/#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>
</header>
<div class="container container--70">
<h1>Aktualny email: {{ user.email }}</h1> <br>
<h1>Imię: {{ user.first_name }}</h1><br>
<h1>Nazwisko: {{ user.last_name }}</h1><br>
<h1>Przekazane datki: </h1>

{% for donation in user.donation_set.all %}
<h3>
<ul>
    <li><div class="container">Dla kogo: <strong>{{ donation.institution.name }}</div></span></li><br>
    <div class="container">Przekazane przedmioty:</div><br>
    {% for category in donation.categories.all %}
    <li><div class="container"><strong>{{ category.name }}</strong></div></li><br>
    {% endfor %}
    <li><div class="container">Ilość 60L worków: <strong>{{ donation.quantity}}</strong></div></li><br>
    <li><div class="container">Data odbioru: <strong>{{ donation.pick_up_date }}</strong></div></li><br>
    <li><div class="container">Godzina odbioru <strong>{{ donation.pick_up_time }}</strong></div></li><br>
</ul></h3><br>
{% endfor %}
</div>

{% endblock content %}
{% block footer %}
{% endblock footer %}